while True:
    code = input("> ")
    result = code.replace(" - ", "#-#")
    code = code.replace("-", " - ")
    code = code.replace("#-#", " - ")
    code = code.replace(")*(", ") * (")
    code = code.replace("x1", "A1[0]")
    code = code.replace("x2", "A2[0]")
    code = code.replace("x3", "B1[0]")
    code = code.replace("x4", "B2[0]")
    code = code.replace("y1", "A1[1]")
    code = code.replace("y2", "A2[1]")
    code = code.replace("y3", "B1[1]")
    code = code.replace("y4", "B2[1]")
    print(code)